export type Snippet = {
  id: string; // UUID v4, generated by the API
  title: string;
  language: string;
  code: string;
  createdAt: string; // ISO 8601, set by the API
};

export type CreateSnippetInput = Pick<Snippet, 'title' | 'language' | 'code'>;
